version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    environment:
      - PORT=10000
    volumes:
      - ./app:/app
      - ./requirements.txt:/app/requirements.txt
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge